### ISSUE TITLE
Is zimbra ose 2fa has token manager?

### ISSUE THREAD

**Issue by cvhoangpt** [maldua-suite/zimbra-ose-2fa#16]
Hi there, can you show me token manager of ose 2fa?. So when user is missing TOTP, what do they do?
I see guide to download passcode number but in some case they leave this pdf.

**Comment by cvhoangpt** [comment]
@adriangibanelbtactic please help

**Comment by adriangibanelbtactic** [comment]
> Hi there, can you show me token manager of ose 2fa?. So when user is missing TOTP, what do they do? I see guide to download passcode number but in some case they leave this pdf.

If I'm not mistaken you should disable the user as per [Disabling 2FA for an user section](https://github.com/maldua-suite/zimbra-ose-2fa?tab=readme-ov-file#disabling-2fa-for-an-user), let the user log in and then they should be able to setup again their 2FA as if it was an account that never set it up.

Please test this with some test accounts and report back because it would be nice to have it documented.

Also check: [Re: Reset 2F Auth Secret of an account](https://forums.zimbra.org/viewtopic.php?p=312836#p312836) explanation where how to enable it again might be explained:

> As a Admin, after setting zimbraFeatureTwoFactorAuthAvailable as TRUE.
> You(Admin) need to set zimbraTwoFactorAuthEnabled as FALSE
> so that user can login with username and password only and
> can setup fresh 2FA from Preference > Accounts > Account security.
>
>```
>zmprov ma test1@`zmhostname` zimbraFeatureTwoFactorAuthAvailable TRUE
>zmprov ma test1@`zmhostname` zimbraTwoFactorAuthEnabled FALSE
>```

Please help me with these instructions after your tests and write some nice instructions that don't involve CLI so that I can improve the README.

Thanks !

**Comment by cvhoangpt** [comment]
Many thanks, so do you know how to prevent brute-force attacks via imap or pop3 ?

**Comment by adriangibanelbtactic** [comment]
> Many thanks, so do you know how to prevent brute-force attacks via imap or pop3 ?

Well, that's a bit offtopic, you could use fail2ban I guess. Many documentation is out there explaining how to use it with Zimbra.

In any case Brute-force imap while having 2FA enabled is not as easy because the cracker is targeting an specific password, not a [hash collision](https://privacycanada.net/hash-functions/hash-collision-attack/) as it happens when 2FA is not enabled.

So, yes, enabling 2FA, sort of prevents brute-force attacks being successful.

**Comment by adriangibanelbtactic** [comment]
> I can only say thank you very much, and I will do what you just mentioned.

Cool.

Waiting for your suggested 2FA token reset instructions so that we can improve the documentation.

**Comment by adriangibanelbtactic** [comment]
Deceived by @cvhoangpt not having contributed back :( .

Closing the issue.
